replace passwords, secrets, other values in yamls by environment vari…
NoxOrg/Nox.Lib.V6 pull request #195
Opened 2023-06-13 13:51 UTC by rochar

…ables

issue #87
yaml will be parsed and Macros will be replaced by environment variables if found Macro example ${env:DB_USER}

2023-06-13 15:36 UTC, andresharpe requested changes

2023-06-13 15:36 UTC, andresharpe commented on src/Nox.Core/Helpers/TextMacros/TextEnvironmentVariableMacroParser.cs
> +    private readonly Regex _regex = new Regex(@"\$\{env:\S+\}", RegexOptions.Compiled, TimeSpan.FromMilliseconds(10000));
We adopted the gitflow variable naming convention in Nox.Cli and should do the same for Nox.Lib. Eg.

${{ env.THE_VARIABLE }}

So should ideally match **${{** followed by no or multiple spaces, then **env.**, then the variable name, again zero or more spaces, closing with **}}**.

2023-06-13 15:36 UTC, andresharpe commented on src/Nox.Core/Helpers/ProjectConfigurator.cs
> +            yamlResult = macroParser.Parse(yamlText);
There is a bug here - won't work for multiple parsers. you are overriding yamlResult with only the last parser values. You are always reading in from the original yamText which will not change - so only last parser results will be applied.

Should be:
```
    internal string ReadDefinitionFile(string fileName)
    {

        Log.Information("Reading definition from {fileName}", fileName.Replace('\\', '/'));

        var yamlText = File.ReadAllText(fileName);

        if(_textMacroParsers is not null)
        {
            foreach (var macroParser in _textMacroParsers)
            {
                yamlText = macroParser.Parse(yamlText);
            }

        }

        return yamlText;
    }
```

2023-06-13 15:36 UTC, andresharpe commented on src/Nox.Core/Helpers/ProjectConfigurator.cs
> +    private readonly ITextMacroParser[] _textMacroParsers;
OPTIONAL: I would remove the 'readonly' - and make Parsers optional. Then simplify the constructor as follows:-
```
    private ITextMacroParser[]? _textMacroParsers;

    public ProjectConfigurator(string designRoot)
    {
        _designRoot = designRoot;
        _deserializer = new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .Build();
    }

    public ProjectConfigurator WithParsers(ITextMacroParser[] textMacroParsers)
    {
        _textMacroParsers = textMacroParsers;
        return this;
    }
```

2023-06-13 15:36 UTC, andresharpe commented on tests/Nox.Core.Tests/YamlConfigurationTests.cs
> +        var configurator = new ProjectConfigurator(appSettings!["Nox:DefinitionRootPath"]!,new ITextMacroParser[]{ new TextEnvironmentVariableMacroParser(environmentProvider.Object)});
OPTIONAL:
If you use the ".WithParsers" approach, then this will become.

```
        var sut = new ProjectConfigurator("./")
            .WithParsers( new ITextMacroParser[] { new TextEnvironmentVariableMacroParser(environmentProvider.Object) }
        );
```

2023-06-13 15:39 UTC, rochar commented on src/Nox.Core/Helpers/ProjectConfigurator.cs
> +            yamlResult = macroParser.Parse(yamlText);
you are right, I will create a test to ensure that does not happen again

2023-06-14 10:59 UTC, rochar commented
We will hold the PR until the Nox.Solution is ready and this will be merge to that repo with the necessary adjustments

2023-06-14 10:59 UTC, closed without merging